version: "3.9"
services:
  spring-app:
    build: .
    ports:
      - 8080:8080
    environment:
      VETAPP_DB_PASS: tHLRmWM40Epe
      VETAPP_DB_URL: jdbc:postgresql://ep-autumn-unit-a43rvl4o.us-east-1.pg.koyeb.app/
      VETAPP_DB_NAME: koyebdb
      VETAPP_DB_USER: koyeb-adm

    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: vet_app_user
      POSTGRES_PASSWORD: postgresPassword
      POSTGRES_DB: vetapp
